### ISSUE TITLE
admin_level=6 and maritime boundaries

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/osm-boundaries#13]
Hi! I've tried to display boundaries with `admin_level=6` and it seems that there is no `boundary=maritime` for this boundaries.

![2015-04-30 18 05 00](https://cloud.githubusercontent.com/assets/533564/7413827/54943058-ef68-11e4-8dc5-f0cdd904cbd3.png)

Here is an example — maritime is red and boundaries with `admin_level=6` is green. So is it OSM issue or something else?

**Comment by ajashton** [comment]
This is probably a OSM data issue. Maritime tagging is mostly complete for admin_level=2, but is less complete for each subsequent level. The maritime ways need to be tagged with `maritime=yes` or one of [these key/value combinations](https://github.com/mapbox/osm-boundaries/blob/master/process-boundaries.js#L10-L19) in order to be correctly classified here.

**Comment by stepankuzmin** [comment]
Thanks @ajashton! Closing issue.
